

export const palNav = [{
      title: 'Home',
      fafa: 'fa fa-fw fa-dashboard',
      id: 'think_dashboard',
      childId: 'think_dashboardChildID',
      childIdHash: '#think_dashboardChildID',
      routerLink: ['insight-dashboard'],
      disabled: false,
      visible: true,
}, {
      title: 'Processing',
      fafa: 'fa fa-tasks',
      id: 'headingProcessing',
      childId: 'processingSubMenu',
      childIdHash: '#processingSubMenu',
      disabled: false,
      visible: true,
      children: [{
            title: 'Archive of Feeds',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/archive_of_feeds'],
            disabled: false,
            visible: true,
      }, {
            title: 'Quality Assurance',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/quality_assurance'],
            disabled: false,
            visible: true,
      }, {
            title: 'Push Live and Roll Back',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/push_live_and_roll_back'],
            disabled: false,
            visible: true,
      }, {
            title: 'Dynamic Report',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/dynamic_report'],
            disabled: false,
            visible: true,
      }, {
            title: 'Favorites',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/favorites'],
            disabled: false,
            visible: true,
      }]
}, {
      title: 'Accounts',
      fafa: 'fa fa-calculator',
      id: 'headingAccount',
      childId: 'accountsSubMenu',
      childIdHash: '#accountsSubMenu',
      disabled: false,
      visible: true,
      children: [{
            title: 'Accounts',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/accounts'],
            disabled: false,
            visible: true,
      }, {
            title: 'Favorites',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/favorites'],
            disabled: false,
            visible: true,
      }]
}, {
      title: 'User Management',
      fafa: 'fa fa-tasks',
      id: 'headingUserManagement',
      childId: 'usermanagementSubMenu',
      childIdHash: '#usermanagementSubMenu',
      disabled: false,
      visible: true,
      children: [{
            title: 'Publisher User',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/publisher_users'],
            disabled: false,
            visible: true,
      }, {
            title: 'Library User',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/Library_users'],
            disabled: false,
            visible: true,
      }, {
            title: 'Role',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/role'],
            disabled: false,
            visible: true,
      }, {
            title: 'Create and Manage SUSHI Partners',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/SUSHI_partners'],
            disabled: false,
            visible: true,
      }]
}, {
      title: 'Publisher Setup',
      fafa: 'fa fa-cogs',
      id: 'headingPubisherSetup',
      childId: 'pubisherSetupSubMenu',
      childIdHash: '#pubisherSetupSubMenu',
      disabled: false,
      visible: true,
      children: [{
            title: 'Manage Favorites',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/manage_favorites'],
            disabled: false,
            visible: true,
      }, {
            title: 'Manage Email Alerts',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/email_alerts'],
            disabled: false,
            visible: true,
      }, {
            title: 'Manage Push Live Settings',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/push_live'],
            disabled: false,
            visible: true,
      }, {
            title: 'Manage Library Configuration Options',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/lib_config'],
            disabled: false,
            visible: true,
      }, {
            title: 'Configure Reports For Librarians',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/configure_reports'],
            disabled: false,
            visible: true,
      }]
}, {
      title: 'Publisher Reports',
      fafa: 'fa fa-file-text',
      id: 'headingPublisherReports',
      childId: 'accountsSubMenu',
      childIdHash: '#accountsSubMenu',
      routerLink: ['insight/publisher_reports'],
      disabled: false,
      visible: true,
}, {
      title: 'Sales',
      fafa: 'fa fa-link',
      id: 'headingSales',
      childId: 'saleSubMenu',
      childIdHash: '#saleSubMenu',
      disabled: false,
      visible: true,
      children: [{
            title: 'Trials',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/trials'],
            disabled: false,
            visible: true,
      }, {
            title: 'Sales Report',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/sales_report'],
            disabled: false,
            visible: true,
      }, {
            title: 'Account Search',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/account_search'],
            disabled: false,
            visible: true,
      }, {
            title: 'Create and Manage Sales Users',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/create_and_manage_sales_users'],
            disabled: false,
            visible: true,
      }, {
            title: 'Publisher Level Report Threshold Setting',
            fafa: 'fa fa-angle-right',
            routerLink: [],
            // ['insight/publisher_level_report_threshold_setting']
            disabled: true,
            visible: true,
      }, {
            title: 'Seasonality Adjustment',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/seasonality_adjustment'],
            disabled: false,
            visible: true,
      }, {
            title: 'User Administration',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/user_administration'],
            disabled: false,
            visible: true,
      }, {
            title: 'User Saved Query',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/user_saved_query'],
            disabled: false,
            visible: true,
      }]
}, {
      title: 'Support',
      fafa: 'fa fa-info-circle',
      id: 'headingSupport',
      childId: 'supportSubMenu',
      childIdHash: '#supportSubMenu',
      disabled: false,
      visible: true,
      children: [{
            title: 'Contact Us',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/contactus_insight'],
            disabled: false,
            visible: true,
      }, {
            title: 'FAQs',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/faqs-ieee'],
            disabled: false,
            visible: true,
      }, {
            title: 'View Issue Tracker',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/role'],
            href: 'http://support.mpsinsight.com/secure/Dashboard.jspa',
            disabled: true,
            visible: false,
      }, {
            title: 'System Log',
            fafa: 'fa fa-angle-right',
            routerLink: ['insight/system_log'],
            disabled: false,
            visible: true,
      }]
},
];